name: "Terraforming vnet PR"

on:
    pull_request:
        types:
          - opened
          - synchronize
    #paths:
    #  - 'terraforming-vnet/**/*'

defaults:
  run:
    working-directory: terraforming-vnet

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      BRANCH_NAME: ${{ github.base_ref }}


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.8.5

    - name: Terraform Init
      run: terraform init --backend-config=./config/${{ env.BRANCH_NAME }}.tfbackend

    - name: Terraform Plan
      id: plan
      run: terraform plan --var-file=./tfvars/${{ env.BRANCH_NAME }}.tfvars

    - name: Post Plan Output as Comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          **Terraform Plan**
          ```
          ${{ steps['plan'].outputs.stdout }}
          ${{ steps['plan'].outputs.stderr }}
          ```