name: "Terraforming vnet Merge"

on:
  push:
    branches:
      #- master
      - sandbox
      - preprod
    #paths:
    #  - 'terraforming-vnet/**/*'

defaults:
  run:
    working-directory: terraforming-vnet

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      BRANCH_NAME: ${{ github.event.ref }}


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.8.5

    - name: Terraform Init
      run: terraform init --backend-config=./config/${{ env.BRANCH_NAME }}.tfbackend

    - name: Terraform Plan
      run: terraform plan --var-file=./tfvars/${{ env.BRANCH_NAME }}.tfvars

    - name: Terraform Apply
      run: terraform apply --auto-approve --var-file=./tfvars/${{ env.BRANCH_NAME }}.tfvars